name: Frontend tests
run-name: ${{ github.actor }} launching frontend tests

on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**', '.github/workflows/frontend.yml' ]

defaults:
  run:
    working-directory: frontend
    
jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Build image (frontend)
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build .