name: Frontend tests
run-name: ${{ github.actor }} launching frontend tests

on:
  pull_request:
    branches: [ main ]
    paths: [ 'frontend/**', '.github/workflows/frontend.yml' ]

defaults:
  run:
    working-directory: frontend
    
jobs:
  lint:
    name: Lint (frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install eslint
        run: npm install eslint
      - name: Launch eslint
        run: npm run lint

  format:
    name: Format (frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install prettier
        run: npm install prettier
      - name: Launch prettier
        run: npm run format
    
  build:
    needs: 
      - lint
    runs-on: ubuntu-latest
    name: Build (frontend)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  docker_build:
    needs:
      - build
    runs-on: ubuntu-latest
    name: Build image (frontend)
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: docker build .